name: ENS-Indexer
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: ENSRegistryWithFallback
        address:
          - "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
        handler: src/ENSRegistryEventHandlers.ts
        events:
          - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
            requiredEntities:
              - name: ENSRegistryEventsSummary
          - event: NewOwner(bytes32 indexed node, bytes32 indexed label, address owner)
            requiredEntities:
              - name: DomainNode
              - name: ENSRegistryEventsSummary
          - event: NewResolver(bytes32 indexed node, address resolver)
            requiredEntities:
              - name: DomainNode
              - name: ENSRegistryEventsSummary
          - event: NewTTL(bytes32 indexed node, uint64 ttl)
            requiredEntities:
              - name: DomainNode
              - name: ENSRegistryEventsSummary
          - event: Transfer(bytes32 indexed node, address owner)
            requiredEntities:
              - name: DomainNode
              - name: ENSRegistryEventsSummary
      - name: ETHRegistrarController
        address:
          - "0x253553366Da8546fC250F225fe3d25d0C782303b"
        handler: src/RegistrarControllerEventHandler.ts
        events:
          - event: NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 baseCost, uint256 premium, uint256 expires)
            requiredEntities:
              - name: Account
              - name: Domain
              - name: DomainMeta
              - name: EthRegistrarControllerEventSummary
          - event: NameRenewed(string name, bytes32 indexed label, uint256 cost, uint256 expires)
            requiredEntities:
              - name: Account
              - name: Domain
              - name: DomainMeta
              - name: EthRegistrarControllerEventSummary
          - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
            requiredEntities:
              - name: EthRegistrarControllerEventSummary
      - name: NameWrapper
        address:
          - 0xD4416b13d2b3a9aBae7AcD5D6C2BbDBE25686401
        handler: src/NameWrapperHandler.ts
        events:
          - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: ApprovalForAll(address indexed account, address indexed operator, bool approved)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: ControllerChanged(address indexed controller, bool active)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: ExpiryExtended(bytes32 indexed node, uint64 expiry)
            requiredEntities:
              - name: NameWrapperEventsSummary
              - name: DomainNode
          - event: FusesSet(bytes32 indexed node, uint32 fuses)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: NameUnwrapped(bytes32 indexed node, address owner)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: NameWrapped(bytes32 indexed node, bytes name, address owner, uint32 fuses, uint64 expiry)
            requiredEntities:
              - name: DomainMeta
              - name: NameWrapperEventsSummary
              - name: DomainNode
          - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
            requiredEntities:
              - name: NameWrapperEventsSummary
          - event: URI(string value, uint256 indexed id)
            requiredEntities:
              - name: NameWrapperEventsSummary
