name: Import-Test
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: ENSRegistryWithFallback
        address:
          - '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e'
        handler: src/EventHandlers.ts
        events:
          - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
            requiredEntities:
              - name: Account
              - name: EventsSummary
          - event: NewOwner(bytes32 indexed node, bytes32 indexed label, address owner)
            requiredEntities:
              - name: Account
              - name: Domain
              - name: EventsSummary
          - event: NewResolver(bytes32 indexed node, address resolver)
            requiredEntities:
              - name: Domain
              - name: EventsSummary
          - event: NewTTL(bytes32 indexed node, uint64 ttl)
            requiredEntities:
              - name: Account
              - name: Domain
              - name: EventsSummary
          - event: Transfer(bytes32 indexed node, address owner)
            requiredEntities:
              - name: Account
              - name: Domain
              - name: EventsSummary
      - name: ETHRegistrarController
        address:
          - '0x253553366Da8546fC250F225fe3d25d0C782303b'
        handler: src/RegistrarControllerEventHandler.ts
        events:
          - event: NameRegistered(string name, bytes32 indexed label, address indexed owner, uint256 baseCost, uint256 premium, uint256 expires)
            requiredEntities:
              - name: EthRegistrarControllerEventSummary
          - event: NameRenewed(string name, bytes32 indexed label, uint256 cost, uint256 expires)
            requiredEntities:
              - name: EthRegistrarControllerEventSummary
          - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
            requiredEntities:
              - name: EthRegistrarControllerEventSummary
